import {useEffect,useState} from "react";
import {api} from "../../api";
import type {Project} from "../../types";
type Preview={sha256:string;projects:{id:string;name:string;methodology:string}[];counts:Record<string,number>;errors:string[];warnings:string[];applied:boolean;already_applied?:boolean};
export function Migration({projects,onApplied}:{projects:Project[];onApplied:()=>Promise<void>}){
 const [file,setFile]=useState<File|null>(null),[source,setSource]=useState("PMO anterior"),[mapping,setMapping]=useState<Record<string,string>>({}),[globalProject,setGlobal]=useState(""),[preview,setPreview]=useState<Preview|null>(null),[validated,setValidated]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[batches,setBatches]=useState<{id:string;filename:string;created_at:string}[]>([]);
 const reload=async()=>setBatches(await api('/migrations'));
 useEffect(()=>{void reload().catch(e=>setError(e.message));},[]);
 const invalidate=()=>setValidated(false);
 async function submit(apply=false){if(!file)return;setBusy(true);setError("");try{const form=new FormData();form.set('file',file);form.set('source',source);form.set('project_map',JSON.stringify(mapping));form.set('global_project',globalProject);if(apply)form.set('confirm_hash',preview?.sha256||'');const result=await api('/migrations/pohub/'+(apply?'apply':'preview'),{method:'POST',body:form});setPreview(result);setValidated(!result.errors.length);if(result.applied){await onApplied();await reload();}}catch(e){setError((e as Error).message);setValidated(false);}finally{setBusy(false);}}
 return <section className="panel"><h2>Migrar archivo .pohub</h2><p>Selecciona una exportación del PMO 3.1 (esquema 3). Primero se valida sin guardar cambios. Asigna cada proyecto a uno existente o crea uno nuevo; la importación conserva fichas existentes y publicaciones.</p><fieldset disabled={busy}><label>Archivo de origen<input type="file" accept=".pohub,.json" onChange={e=>{setFile(e.target.files?.[0]||null);setPreview(null);setMapping({});invalidate();}}/></label><label>Nombre estable del origen<input required maxLength={200} value={source} onChange={e=>{setSource(e.target.value);invalidate();}}/></label><button disabled={!file} onClick={()=>void submit()}>Leer y validar archivo</button>
 {preview&&<><h3>Destino de proyectos</h3>{preview.projects.map(p=><label key={p.id}>{p.name} · {p.methodology}<select value={mapping[p.id]||""} onChange={e=>{setMapping({...mapping,[p.id]:e.target.value});invalidate();}}><option value="">Seleccionar destino</option><option value="__new__">Crear proyecto nuevo</option>{projects.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>)}<label>Proyecto para agenda y asignaciones sin proyecto en el origen<select value={globalProject} onChange={e=>{setGlobal(e.target.value);invalidate();}}><option value="">Seleccionar si existen registros globales</option>{preview.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><h3>Contenido detectado</h3><ul>{Object.entries(preview.counts).map(([k,v])=><li key={k}>{k}: {v}</li>)}</ul>{preview.warnings.map((w,i)=><p key={i}>{w}</p>)}{preview.errors.length>0&&<div role="alert"><h3>Pendiente de resolver</h3><ul>{preview.errors.map((e,i)=><li key={i}>{e}</li>)}</ul></div>}<button onClick={()=>void submit()}>Validar destinos y referencias</button><button className="primary" disabled={!validated||preview.applied} onClick={()=>void submit(true)}>Aplicar importación validada</button>{preview.applied&&<p role="status">{preview.already_applied?"Este archivo ya fue importado; no se duplicaron datos.":"Importación completada. Original y mapa de identidades conservados."}</p>}</>}
 </fieldset>{error&&<p role="alert">{error}</p>}<h3>Importaciones guardadas</h3>{batches.map(b=><p key={b.id}>{b.filename} · {b.created_at.slice(0,10)} · <a href={`/api/migrations/${b.id}/original`}>Descargar original</a></p>)}{!batches.length&&<p>No hay importaciones aplicadas.</p>}</section>;
}
